### ISSUE TITLE
too large fdsets

### ISSUE THREAD

**Issue by kunalmodi** [typhoeus/typhoeus#206]
I've started seeing a bunch of ArgumentError: too large fdsets being thrown by Typheous. I was wondering if anyone had any insight into what that might mean?

```
ArgumentError: too large fdsets
/app/vendor/bundle/ruby/1.9.1/gems/typhoeus-0.3.3/lib/typhoeus/multi.rb:21:in `multi_perform'
/app/vendor/bundle/ruby/1.9.1/gems/typhoeus-0.3.3/lib/typhoeus/multi.rb:21:in `perform'
/app/vendor/bundle/ruby/1.9.1/gems/typhoeus-0.3.3/lib/typhoeus/hydra.rb:95:in `run'
```

I am passing just a single http get request into the typhoeus hydra:

```
request = Typhoeus::Request.new("#{url}",
  :timeout  => 30000,
  :header   => {:Accept => "application/json", 'Content-Type' => "application/json"})

hydra = Typhoeus::Hydra.new
hydra.queue(request)
hydra.run  # exception thrown on this line
response = request.response
```

thanks!

**Comment by schneems** [comment]
I've got a similar error in another project doing network connections and there is painfully little information about this error on the internet.

Any idea what causes this exception? I've got a vauge understanding of an fd_set (http://linux.die.net/man/3/fd_set) is the exception saying the file descriptor is too large, or too many file descriptors are being attempted to be used? How was this issue eventually resolved

**Comment by i0rek** [comment]
Hello @schneems, thanks for reporting. Which version of typhoeus, ethon and libcurl are you running? I assume you are on linux?

**Comment by schneems** [comment]
@i0rek unfortunately it's not using Typhoeus, it is on Heroku cedar app so linux and was an issue with an older PG gem and AR network calls. There's only like 2 or three issues for "ArgumentError: too large fdsets" so I took a shot asking here.

```
~ $ curl -V
curl 7.19.7 (x86_64-pc-linux-gnu) libcurl/7.19.7 OpenSSL/0.9.8k zlib/1.2.3.3 libidn/1.15
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
~ $ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=10.04
DISTRIB_CODENAME=lucid
DISTRIB_DESCRIPTION="Ubuntu 10.04.4 LTS"
```

**Comment by i0rek** [comment]
I see. I am sorry but I don't know what to do about it in this case. Typhoeus uses Ethon to deal with libcurl. There is a libc interface to ask for the correct size: https://github.com/typhoeus/ethon/blob/16cb318835bf22bfb2d13858e4ea1a3cc1a080f2/lib/ethon/curls/classes.rb#L23. Maybe that was not respected by something in your stack/

**Comment by schneems** [comment]
No worries, that's enough to help. Sorry for bugging you on a totally unrelated issue, thanks for the response :+1:

**Comment by i0rek** [comment]
Sure, good luck!
