### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by hanshasselberg** [typhoeus/typhoeus#214]
As suggested here: https://groups.google.com/forum/?fromgroups=#!topic/typhoeus/9wr55BLnCdE

**Comment by erwanlr** [comment]
Can this be really used to throttle the requests ? (e.g 1 request per second like you said in a comment above). It doesn't seem from the description of the option and the fact that this attribute is applied to the request and not hydra.

Currently looking if Typhoeus can throttle the hydra's requests.

**Comment by i0rek** [comment]
> But something like 1 request per second was requested, which is not possible atm

I said it doesn't work :(
