### ISSUE TITLE
Header Response not case insensitive

### ISSUE THREAD

**Issue by dallasrpi** [typhoeus/typhoeus#227]
Its pretty common to have headers use "Content-Length" or "Content-length"  or "Etag" vs "ETag" .  This presents a problem when you don't know which version is coming down the pike.   An obvious work around is to iterate the headers object and lowercase the keys but just noting it makes this feature a little less usable.

**Comment by ric2b** [comment]
This still happens with `fetch()`, would it make sense to reopen this issue or should I create a new one?
