### ISSUE TITLE
Ethon::Errors::InvalidOption: The option: disable_ssl_peer_verification is invalid.

### ISSUE THREAD

**Issue by benhamill** [typhoeus/typhoeus#270]
I've got version 0.6.1 of typhoeus and 0.5.9 of ethon. I'm using faraday with the typhoeus adapter and when I make any request, I get this:

```
Ethon::Errors::InvalidOption: The option: disable_ssl_peer_verification is invalid.
Please try ssl_verifypeer instead of disable_ssl_peer_verification.
from /home/ben/.rbenv/versions/1.9.3-p374/lib/ruby/gems/1.9.1/gems/ethon-0.5.9/lib/ethon/easy.rb:254:in `block in set_attributes'

```

This seems like a pretty simple fix, but since both repos are in the same Organization, I thought maybe there was something I didn't know. Would this be a good pull request to make?

**Comment by perlun** [comment]
FYI - if you are using Faraday w/ the `elasticsearch` gem, **do not use this approach**:

```ruby
require 'typhoeus/adapters/faraday'
```

We have seen it causing intermittent errors https://github.com/elastic/elasticsearch-ruby/issues/221. I suspect that the Typhoeus Faraday adapter is not entirely thread safe, or something to the like. The link has more details, but the error is that _perfecly valid HTTP requests_ can give a spurious HTTP 397 error (maybe other error codes as well).

Removing this require fixed it altogether.
