### ISSUE TITLE
Use the curl --cookie-jar option

### ISSUE THREAD

**Issue by erwanlr** [typhoeus/typhoeus#285]
Is there a way to use the curl --cookie-jar option with Typhoeus ?

I'm currently stuck with a website which does an infinite redirections loop because it wants to set the cookie :/

See https://github.com/wpscanteam/wpscan/issues/144

**Comment by sebbean** [comment]
dead in the water :'(

**Comment by sebbean** [comment]
thankfully https://github.com/jnunemaker/httparty

**Comment by Zapotek** [comment]
@sebbean Huh? The option is right there in the [README](https://github.com/typhoeus/typhoeus#cookies).

**Comment by sebbean** [comment]
@Zapotek yea i'm using that option - doesn't actually 'flush the data to file'

https://github.com/typhoeus/typhoeus/issues/291
