### ISSUE TITLE
[ERROR] activation#notify (NameError) "uninitialized constant Admin::ActivationController::Typhoeus"

### ISSUE THREAD

**Issue by ramza1** [typhoeus/typhoeus#288]
i get this error when using the gem 
this is my controller code

[ERROR] activation#notify (NameError) "uninitialized constant Admin::ActivationController::Typhoeus"

i am using rails 3.2.13 and ruby 2.0.0-p0

any help thanks

**Comment by pisaq** [comment]
::Typhoeus
(i know it was 3 years ago)
