### ISSUE TITLE
Proxy type is ignored when passed as a String

### ISSUE THREAD

**Issue by Zapotek** [typhoeus/typhoeus#399]
Hey guys,

Looks like the `proxytype` option is ignored.

Proxy setup:
```
ssh -v -N -D 0.0.0.0:1080 localhost
```

Failing:
```
Typhoeus.get( 'http://google.com', proxy: 'localhost:1080', proxytype: 'socks5' ).code
#=> 0
```

Passing:
```
Typhoeus.get( 'http://google.com', proxy: 'socks5://localhost:1080' ).code
#=> 302
```

Tested with Typhoeus v0.6.9.

Cheers

**Comment by i0rek** [comment]
It is fixed: https://github.com/typhoeus/ethon/commit/ef42e14ad2abdcf2a0d6bfdef061193ad22dab4c.
