### ISSUE TITLE
Can't convert Symbol into Integer error

### ISSUE THREAD

**Issue by zubinix** [typhoeus/typhoeus#412]
I have a program that runs many threads in parallel, each which do the same thing i.e. send a request and analyse the response. When the load is below around 50 threads no errors are generated by Typhoeus but as more threads are run in parallel I start to see this error:

/home/ubuntu/.rvm/gems/jruby-1.7.8/gems/typhoeus-0.6.9/lib/typhoeus/response/informations.rb
27
return_message

Does anyone know why this error is occurring?

**Comment by i0rek** [comment]
@Zapotek thanks for looking into it. I was able to reproduce your problem until I fixed something. Could you point your ethon to this branch: https://github.com/typhoeus/ethon/tree/easy_code and check if it helps?

**Comment by Zapotek** [comment]
@i0rek No problem. The change seems to have done the trick, the error went away. :) Cheers man.

**Comment by i0rek** [comment]
I merged the fix and released a new ethon version.
