### ISSUE TITLE
It is possible to cancel a resquest when making streaming of the body?

### ISSUE THREAD

**Issue by luccasmaso** [typhoeus/typhoeus#423]
As it is on the docs below to stream a request, how can I cancel it if it's a long request?

```
downloaded_file = File.open 'huge.iso', 'wb'
request = Typhoeus::Request.new("www.example.com/huge.iso")
request.on_headers do |response|
  if response.code != 200
    raise "Request failed"
  end
end
request.on_body do |chunk|
  downloaded_file.write(chunk)
end
request.on_complete do |response|
  downloaded_file.close
  # Note that response.body is ""
end
request.run
```

In my need, for example, inside `request.on_headers` I want to make some validation on the content-type, and if it is not text/html, I don't want to keep downloading the file.

Thanks!

**Comment by i0rek** [comment]
@luccasmaso yes it is. Return `:abort` from `on_body`. Here is the commit: https://github.com/typhoeus/ethon/commit/61178720.

**Comment by i0rek** [comment]
I guess the implementation is incomplete since it is not possible to abort in `on_headers` yet...

**Comment by luccasmaso** [comment]
Thanks! :abort solved the problem.
