### ISSUE TITLE
Issue with nested query

### ISSUE THREAD

**Issue by PericlesTheo** [typhoeus/typhoeus#424]
I am not sure whether this is an issue with the gem or the endpoint I'm hitting but I get a 500 code with nested queries.

The request looks like this:

``` ruby
params = {
  'title' => 'Mr',
  'first_name' => 'Chandler',
  'last_name' => 'Bing',
  'email' => 'chandler_bing@friends.com',
  'addresses' => [
    {
      'flat_number' => '4',
      'street' => 'Main Street',
       'town' => 'London',
       'postcode' => 'SW4 6EH',
        'country' => 'GBR'
      }
    ]
  }

Typhoeus.post('api_endpoint', body: params)
```

To get around the issue, I am using Rack to build the nested query:

``` ruby
Typhoeus.post('api_endpoint', body: Rack::Utils.build_nested_query(params))
```

**Comment by i0rek** [comment]
This is an issue with Typhoeus. Kind of. Look at the difference:

```ruby
Rack::Utils.build_nested_query(params)
#=> "title=Mr&first_name=Chandler&last_name=Bing&email=chandler_bing%40friends.com&addresses[][flat_number]=4&addresses[][street]=Main+Street&addresses[][town]=London&addresses[][postcode]=SW4+6EH&addresses[][country]=GBR"
Ethon::Easy::Form.new(nil, params)
=> title=Mr&first_name=Chandler&last_name=Bing&email=chandler_bing@friends.com&addresses[0][flat_number]=4&addresses[0][street]=Main Street&addresses[0][town]=London&addresses[0][postcode]=SW4 6EH&addresses[0][country]=GBR
```

This is because the way Rack encodes nested hashes and arrays is ambiguous. Typhoeus adds an array index. We have a middleware to help decoding the params but not the body: http://www.rubydoc.info/github/typhoeus/typhoeus/Rack/Typhoeus/Middleware/ParamsDecoder. Now that I think about it should take care of the body too I think....

**Comment by PericlesTheo** [comment]
Cool, thanks for looking into it. Let me know if I can be of any help!

**Comment by i0rek** [comment]
I was thinking about supporting both ways of params encoding. Do you want to take a stab at it?

**Comment by PericlesTheo** [comment]
yep I can give it a go

**Comment by i0rek** [comment]
Let we know if you need help. I thought about adding a config option in Typhoeus. You could check in Ethon if Typhoeus is defined and then check the config option. That was my plan...

**Comment by PericlesTheo** [comment]
Hey @i0rek I haven't had time to look into this yet(lame!). Still planning on working on it though

**Comment by i0rek** [comment]
@PericlesTheo no worries :)

**Comment by vjt** [comment]
Hi @i0rek and @PericlesTheo, I've added an option to Ethon to encode arrays the Rack way. I've left a *FIXME* in the code for a smelly situation :smiley: - please check it out.

I'm using it now on ifad/hawk@74890c8 and it looks good. What do you think? Opening a pull to let travis do its homework.

Thanks!
