### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by DaveBlooman** [typhoeus/typhoeus#434]
I am using Faraday with Typhoeus as middleware, when using the Typhoeus parallel feature, i'm curious whether it supports `FaradayMiddleware::FollowRedirects` as I can't seem to make it work.  Below is the code i'm working with, in my case, `urls` is an array of paths such as /home or /contact with a base path of www.example.com.

```ruby
manager = Typhoeus::Hydra.new(:max_concurrency => 100)

request = Faraday.new(:parallel_manager => manager, :url => base, :ssl => { :verify => false }, :headers => headers[:headers]) do |faraday|
  faraday.use FaradayMiddleware::FollowRedirects
  faraday.adapter :typhoeus
end

@responses = []

request.in_parallel(manager) do
  urls.each do |page_path|
    @responses << [request.get(page_path), page_path]
  end
end

@responses.each do |array|
  status = array.first.status
  path = array.last
 # Do something with result
end
```

**Comment by i0rek** [comment]
```
Typhoeus.get("www.example.com", followlocation: true)
```

follows redirects. I guess you have to give this option. The middleware is not supported because it works differently in Typhoeus. Typhoeus doesn't even know about them, they are handled directly by libcurl.

**Comment by DaveBlooman** [comment]
Thanks for the info.  Typhoeus supports everything I need, so I can probably drop Faraday.  How would suggest to implement parallel request in my use case, where an array of urls needs to be passed and the status code retrieved?  Is this the sort of implementation?

```ruby
requests = urls.map do |page_paths|
  request = Typhoeus::Request.new(base + page_paths, followlocation: true)
  hydra.queue(request)
  request
end

hydra.run

responses = requests.map do |request|
  p request.response.code
end
```

**Comment by i0rek** [comment]
yes, that should work.

**Comment by DaveBlooman** [comment]
Thanks, all working great now.
