### ISSUE TITLE
Typhoeus::Response::Informations#redirect_time

### ISSUE THREAD

**Issue by jarthod** [typhoeus/typhoeus#435]
Is there a reason why `redirect_time` is not available ? it seems to be the only missing timing value available in curl. I can do a PR for this but I just want to be sure it is useful ;)

**Comment by i0rek** [comment]
@jarthod thanks for reporting! A pull request would be appreciated (and merged)!

**Comment by jarthod** [comment]
Great, opened https://github.com/typhoeus/ethon/pull/101 and https://github.com/typhoeus/typhoeus/pull/436 to do this.
