### ISSUE TITLE
Request#hydra attribute

### ISSUE THREAD

**Issue by erwanlr** [typhoeus/typhoeus#437]
While doing requests with Hydra, it (hydra) is set as attribute of each request (https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/hydra/queueable.rb#L39, https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/hydra/queueable.rb#L50). As a result, each request queued contains the whole hydra object and therefore all the requests added :o

Is this attribute necessary ?

Script used to reproduce the behaviour:

```ruby
require 'typhoeus'

@hydra = Typhoeus::Hydra.new

def run_hydra(urls)
  urls.each do |url|
    request = Typhoeus::Request.new(url)

    request.on_complete do |response|
      p response.request.url
      return response if response.request.url.match(/2/)
    end
    @hydra.queue(request)
  end

  @hydra.run
end

urls = 10.times.map { |i| "http://google.com/#{i}" }

p run_hydra(urls)
```

I haven't done any test to check the memory used by this, but I would guess that with large number of requests, that would not be negligible.

I then used the monkey patch below to fix it (the queue_front would also need to be modified):

```ruby
module Typhoeus
  class Hydra
    module Queueable
      def queue(request)
        queued_requests << request
      end
    end
  end
end
```

**Comment by i0rek** [comment]
My first thought was that although every request has it, it is shared like in here:

```ruby 
a= 'x'
#=> "x"
b = {a: a}
c = {a: a}
b[:a].object_id
#=> 70178709625260
c[:a].object_id
#=> 70178709625260
```

**Comment by erwanlr** [comment]
Yep, and therefore the memory used is not affected as I thought. However, what's the purpose of this attribute ?

I was debugging code by dumping a response to check if it was the correct one, and ending up with the 2k hydra requests also dumped :o.
I doesn't really affect things in any other way, but was wondering of the usefulness of it :)

**Comment by i0rek** [comment]
I need to know the hydra in the `on_complete` callback so that the next request can be enqueued: https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/easy_factory.rb#L131-133.
