### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by dblooman** [typhoeus/typhoeus#441]
I am trying to load a self signed cert and make a request to a https URL.  Typically in Faraday I would use

``` ruby
Faraday.new  "URL", ssl => {
    :client_cert => OpenSSL::X509::Certificate.new(File.read("cert.pem")),
    :client_key  => OpenSSL::PKey::RSA.new(File.read("cert.pem")),
    :verify      => false }
  ).get
```

In Typhoeus I tried lots of combinations, but can't get it to return anything, here is what I am putting in,

``` ruby
Typhoeus::Request.new "URL",
                 ssl_verifyhost: 0,
                 ssl_verifypeer: false,
                 cainfo: OpenSSL::X509::Certificate.new(File.read "certificate.pem"),
                 sslkey: OpenSSL::PKey::RSA.new(File.read "certificate.pem")

```

In verbose mode, I get the following

``` sh
#<Typhoeus::Response:0x007fb423f55558 @options={:httpauth_avail=>0, :total_time=>0.196678, :starttransfer_time=>0.0, :appconnect_time=>0.160134, :pretransfer_time=>0.160204, :connect_time=>0.046367, :namelookup_time=>0.045832, :effective_url=>"URL_BEING_HTTPS", :primary_ip=>"IP_ADDRESS", :response_code=>0, :request_size=>155, :redirect_count=>0, :return_code=>:recv_error, :response_headers=>"", :response_body=>"", :debug_info=>#<Ethon::Easy::DebugInfo:0x007fb423f5c100 @messages=[]>}, @request=#<Typhoeus::Request:0x007fb423f5d2a8 @base_url="URL_BEING_HTTPS", @original_options={:ssl_verifyhost=>0, :ssl_verifypeer=>false, :cainfo=>#<OpenSSL::X509::Certificate subject=#<OpenSSL::X509::Name:0x007fb423f4fce8>, issuer=#<OpenSSL::X509::Name:0x007fb423f4fbd0>, serial=#<OpenSSL::BN:0x007fb423f4fab8>, not_before=2015-02-25 10:13:44 UTC, not_after=2016-02-25 10:13:44 UTC>, :sslkey=>#<OpenSSL::PKey::RSA:0x007fb423f5d398>}, @options={:ssl_verifyhost=>0, :ssl_verifypeer=>false, :cainfo=>#<OpenSSL::X509::Certificate subject=#<OpenSSL::X509::Name:0x007fb423f4f310>, issuer=#<OpenSSL::X509::Name:0x007fb423f4f130>, serial=#<OpenSSL::BN:0x007fb423f4f0b8>, not_before=2015-02-25 10:13:44 UTC, not_after=2016-02-25 10:13:44 UTC>, :sslkey=>#<OpenSSL::PKey::RSA:0x007fb423f5d398>, :headers=>{"User-Agent"=>"Typhoeus - https://github.com/typhoeus/typhoeus"}, :maxredirs=>50}, @response=#<Typhoeus::Response:0x007fb423f55558 ...>, @on_complete=[], @on_failure=[]>>
```

When using verbose mode, I can se the cert being loaded, but I must be missing an option, any ideas?

**Comment by AvnerCohen** [comment]
@DaveBlooman Your config seem fine. Response sent back from the downstream libcurl is ````:recv_error````, the description of the error (http://curl.haxx.se/libcurl/c/libcurl-errors.html) "Failure with receiving network data." , doesn't give much.

However, http://forum.whmcs.com/showthread.php?69019-CURL-Error-56-Recv-failure-Connection-reset-by-peer directing to http://forum.directadmin.com/showthread.php?t=46801 , suggest that there might be an error with particular libcurl version (7.31 I think) that is effected.

Could this be your issue ?
Are you seeing the same behaviour with different libcurl versions, or is it isolated to a specific machine?
also, do you see the same with multiple Ruby versions? which one do you use?

HTH

**Comment by DaveBlooman** [comment]
I have tried on a different machine with a different ruby version, one OSX, one Debian, still no joy.  When just using Curl, I use curl -k --cert /app/certificate.pem http://URL.com, this works fine.  Is it possible an option isn't being handed to Curl?

**Comment by xhh** [comment]
@DaveBlooman according to [the source code](https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/adapters/faraday.rb#L119), the option name corresponding to `client_cert` of Faraday is named `sslcert` in Typhoeus, have you tried this one?

**Comment by michaelirey** [comment]
Any update on this issue, I am having the same problem. The server claims I am not sending over the client certificate. I can get this to work with HTTParty and curl from the command line.

**Comment by i0rek** [comment]
@DaveBlooman @michaelirey is there a way I can reproduce this?

**Comment by samwoods1** [comment]
I also ran into this and I think it is related to this:
https://github.com/bagder/curl/issues/283
I tried converting my cert to p12 format, and though curl supports the settings to use that, I couldn't get it to work with typhoeus.  I ended up installing the OpenSSL version of curl on my mac and that seems to have resolved the issue.
It would be great if you typhoeus could determine the curl version to see if it is using SecureTransport instead of OpenSSL, and in that case convert the cert to p12 format and modify the options sent to libcurl to work.  I think the following options would need to be set: SSLCERT, SSLCERTTYPE and SSLKEYPASSWD.
Thanks!

**Comment by i0rek** [comment]
@samwoods1 thanks for your help! 

> It would be great if you typhoeus could determine the curl version to see if it is using SecureTransport instead of OpenSSL, and in that case convert the cert to p12 format and modify the options sent to libcurl to work.

Sounds like a good idea! I would merge such PR.

**Comment by blacktea** [comment]
I wanted to share the code how I got the thing working on old Ruby 1.8.7 project.

Have in mind that CA_CERTs are crucial for handshake

`    cert_root = File.join(RAILS_ROOT,'lib','cert')
    cert_file = File.join(cert_root, 'my.pem')
    key_file = File.join(cert_root, 'my.key')
    ca_file = File.join(cert_root, 'comodo_root_ca.crt')

    cert = File.read(cert_file)
    key = File.read(key_file)

    ctx      = OpenSSL::SSL::SSLContext.new
    ctx.cert = OpenSSL::X509::Certificate.new(cert)
    ctx.key  = OpenSSL::PKey::RSA.new(key)
    
	content_type = "text/xml"

    options = {
      :headers => { "Content-Type" => "#{content_type}; charset=UTF-8" },
      :ssl_verifypeer => false,
      :ssl_verifyhost => 0, # Should be 2 - update cert bundle
      :timeout => 30,
      :cainfo => ca_file,
      :sslkey => key_file,
      #:sslkeypasswd => "", # Key file is unprotected
      :sslcert => cert_file
    }

     return Typhoeus::Request.new(
      uri,
      options
    )`

**Comment by priyanka2211** [comment]
Is there any example on how to use P12 or pfx file instead of pem, key, crt?
