### ISSUE TITLE
Why would Typhoeus be hammering my site causing it to crash

### ISSUE THREAD

**Issue by cyarema** [typhoeus/typhoeus#445]
ec2-54-204-92-226.compute-1.amazonaws.com - - [01/Apr/2015:11:07:49 -0500] "HEAD /publications/ HTTP/1.1" 403 - "-" "Typhoeus - https://github.com/typhoeus/typhoeus"

The above keeps either slowing my site down or crashing it entirely. It happens every couple days. 

It's a Wordpress site. How do I get this to stop?

**Comment by andremedeiros** [comment]
Hi. 

Typhoeus is an HTTP client, so this line tells me that someone is using it to access your website.

Because the issues are for issues with the gem itself, there isn't much we can do to help out :-(

Good luck.

**Comment by Zapotek** [comment]
You could blacklist it by user agent (`Typhoeus - https://github.com/typhoeus/typhoeus`).
You can't do much other than that.

**Comment by rl421403** [comment]
Same with me. My website is also down because of this.

    54.147.157.193 - - [13/Apr/2015:22:18:22 +0000] "HEAD /about/ HTTP/1.1" 200 - "-" "Typhoeus - https://github.com/typhoeus/typhoeus"

The above keeps either slowing my site down or crashing it entirely. How do I get this to stop?

**Comment by Zapotek** [comment]
You're not by any chance also using Wordpress are you?

**Comment by Zapotek** [comment]
Btw that IP address belongs to Amazon AWS, it looks like someone's enumerating files and directories, probably as part of an unauthorized vulneravility scan.

You should contact Amazon AWS, there's nothing we can do.

**Comment by rl421403** [comment]
Yes, I am using WordPress. You said something about blocking user agent. How to do that on Linux server?

**Comment by Zapotek** [comment]
I've no idea, depends on your firewall config. You should contact your hosting provider, maybe hey can help you out.

**Comment by i0rek** [comment]
using a cdn would be another option.
