### ISSUE TITLE
Rspec style consecutive return values for Typhoeus.stub

### ISSUE THREAD

**Issue by benaldred** [typhoeus/typhoeus#453]
I am working on a project where I need to test different responses that are running through Hydra.

The current stub method is really good for a single stub response but not if you want flexibility (unless I am missing something?)

I ended up doing:

```ruby
r1 = Typhoeus::Response.new(code: 200, body: xml_for_one, time: 0.3)
r2 = Typhoeus::Response.new(code: 200, body: xml_for_two, time: 0.3)
# use rspec to setup sequential return values
allow(Typhoeus::Response).to receive(:new).and_return(r1, r2)
```

The above code still makes the HTTP call.

However I would really like to do:

```ruby
r1 = Typhoeus::Response.new(code: 200, body: xml_for_one, time: 0.3)
r2 = Typhoeus::Response.new(code: 200, body: xml_for_two, time: 0.3)
Typhoeus.stub(/example/).and_return(r1, r2)
```

Is there already a solution to this but not documented? Would this be useful?

**Comment by i0rek** [comment]
Thanks for the suggestion!
`and_return` is already a bit more powerful then one might think. It accepts a block: https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/expectation.rb#L131-140.

**Comment by i0rek** [comment]
This is the PR it was coming from: https://github.com/typhoeus/typhoeus/pull/275. Does that help? If not I would merge a PR providing that functionality.

**Comment by i0rek** [comment]
closing since the PR has been merged. thanks!
