### ISSUE TITLE
around filter to implement logging

### ISSUE THREAD

**Issue by tute** [typhoeus/typhoeus#454]
We just monkey patched typhoeus to implement some internal logging in our app. Would you accept a PR that adds an around filter before calling the network, so users can implement this using the public interface rather than monkey patching?

See example of what we have in mind: http://stackoverflow.com/a/3047515/356060

Thank you!

**Comment by i0rek** [comment]
I would be open for something like that. Although when using the hydra it is going to be very hard to be accurate since this is out of control of Typhoeus.

**Comment by tute** [comment]
Thank you! We are using Hydra too, and it would be confusing to have an around filter working "some" times, so I'll close this issue. Best!
