### ISSUE TITLE
Handling a sequence of requests

### ISSUE THREAD

**Issue by zubinix** [typhoeus/typhoeus#455]
Hi all

Has anyone tried to use the request.on_complete method to execute an array of requests in sequential order? I keep getting this error:

```
 typhoeus/hydra/queueable.rb:39:in `queue': undefined method `hydra=' for nil:NilClass (NoMethodError)
```

most probably because I'm accessing a variable thats not defined in the on_complete callback. How to structure the callback so that it refers to the next request in the array?

```
# array of requests
reqs = Array.new

foreach request
  r = Typhoeus::Request.new....
  reqs.push r
end

# chain requests
for i in 0..(reqs.size-1)
  current_req = reqs[i]
  next_req = reqs[i+1]

  if i < reqs.size-1    # last request has no chain
    current_req.on_complete do |response|
      error handling.....

      # queue next request in sequence
      $hydra.queue(next_req)          <- undefined method error here
    end
  end
end
```

Maybe I'm missing something obvious? My goal is to use Hydra to asynchronously perform multiple streams of requests in parallel.

**Comment by i0rek** [comment]
sorry for chiming in so late, I must've overlooked your issue. what you want should be done automatically when setting the option `max_concurrency = 1` on the hydra. That way you let typhoeus do the heavy lifting. let me know if you still run into problems then.

in your code example I don't see where you create the hydra.

**Comment by i0rek** [comment]
you could also not use the hydra and just `Typhoeus::Request.new().run` in the order you want it to be.
