### ISSUE TITLE
Command to block external connections in testing environment?

### ISSUE THREAD

**Issue by Fedcomp** [typhoeus/typhoeus#461]
Can we have command to block external requests during unit tests? so if some external url being called without stubbing typhoeus raises error.
If we already have it, some examples under stubbing in documentation please?

**Comment by i0rek** [comment]
There is something like that: https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/config.rb#L29. I would be happy to merge a PR for the docs!
