### ISSUE TITLE
Is is possible to specify ciphers?

### ISSUE THREAD

**Issue by genegc** [typhoeus/typhoeus#464]
In curl, it would look like: `curl --ciphers RC4-SHA https://my.example.com`
I haven't been able to figure out how I can pass through a cipher list using Typhoeus.
Is it possible?

**Comment by i0rek** [comment]
@genegc there is the option `cipher_list` in ethon: https://github.com/typhoeus/ethon/blob/master/lib/ethon/curls/options.rb#L428 which you could try using. Some options are present, but not properly implemented, that could be one of them. You are the first one asking for it I believe. It is worth a shot I believe. 
Let me know what happens.

**Comment by genegc** [comment]
Sorry about that - I didn't see it.
I tried it out and it worked - it solved the issue I was having.

I had an issue connecting to a particular server over ssl and found that when using curl, I could only connect to the server when I specified the cipher list. So with this ssl_cipher_list option, I was able to incorporate that same workaround in my code.
Thanks.
