### ISSUE TITLE
Authorization specified as Bearer, but headers sent include Basic and Bearer

### ISSUE THREAD

**Issue by genegc** [typhoeus/typhoeus#469]
I'm using Typhoeus to send a get request:
`Typhoeus.get( "#{@host}/ws/v1/metadata", headers: { Authorization: "Bearer #{@token}", Accept: 'application/JSON', 'Content-Type'=>'application/JSON', verbose: true })`

for some reason, the headers being sent look like:
```
Authorization: Basic xxxxxzFMy1iNDYwLTFkMzNiNzA4NWZlMg==
Host: xyz.someserver.com
User-Agent: Typhoeus - https://github.com/typhoeus/typhoeus
Authorization: Bearer 888xy96f-f3cf-4c0a-bfa8-88bd2d14x8x8
Accept: application/JSON
Content-Type: application/JSON
```

I don't know why that first `Authorization: Basic` is being included, but it appears to be preventing the request from being authenticated.

I have the same code working in a different env using ruby 1.9.3 and the only difference I see in the request being sent is that the extraneous `Authorization: Basic` is not being sent in the header.

Is this a known issue? Any thoughts?

**Comment by i0rek** [comment]
@genegc Thanks for reporting. I tried to reproduce it with libcurl 7.44.0 and I couldn't:

```ruby
require 'typhoeus'
Typhoeus.get( "hans.io/about", headers: { Authorization: "Bearer FUBAR", Accept: 'application/JSON', 'Content-Type'=>'application/JSON'}, verbose: true)
#   Trying 185.31.19.133...
# Connected to hans.io (185.31.19.133) port 80 (#0)
# GET /about HTTP/1.1
# Host: hans.io
# User-Agent: Typhoeus - https://github.com/typhoeus/typhoeus
# Authorization: Bearer FUBAR
# Accept: application/JSON
# Content-Type: application/JSON
# ...
```

**Comment by genegc** [comment]
Thanks for the response. 
I was using libcurl 7.40.0.0 (in a windows env) and tried several different versions of typhoeus (0.7.1, 0.7.2, 0.7.3).
Upgrading libcurl to 7.44.0 resolved the issue.
Much appreciated!

**Comment by i0rek** [comment]
Glad it works!
