### ISSUE TITLE
Getting status: 0 when I run more than 10 requests at once

### ISSUE THREAD

**Issue by asross** [typhoeus/typhoeus#480]
I'm getting a strange issue where Typhoeus is returning empty responses with status: 0, but only when I make more than 10 requests at once.

Here's the ethon output when I run 12 requests at the same time (the 400s are ok and expected, the 0s are bad):

```
ETHON: started MULTI
ETHON:         performed EASY effective_url=<URL> response_code=0 return_code=recv_error total_time=0.280002
ETHON:         performed EASY effective_url=<URL> response_code=0 return_code=recv_error total_time=0.300416
ETHON:         performed EASY effective_url=<URL> response_code=400 return_code=ok total_time=0.365894
ETHON:         performed EASY effective_url=<URL> response_code=400 return_code=ok total_time=0.371102
ETHON:         performed EASY effective_url=<URL> response_code=400 return_code=ok total_time=0.372054
ETHON:         performed EASY effective_url=<URL> response_code=400 return_code=ok total_time=0.467612
ETHON:         performed EASY effective_url=<URL> response_code=400 return_code=ok total_time=0.468912
ETHON:         performed EASY effective_url=<URL> response_code=400 return_code=ok total_time=0.475045
ETHON:         performed EASY effective_url=<URL> response_code=400 return_code=ok total_time=0.484486
ETHON:         performed EASY effective_url=<URL> response_code=400 return_code=ok total_time=0.484521
ETHON:         performed EASY effective_url=<URL> response_code=400 return_code=ok total_time=0.484609
ETHON:         performed EASY effective_url=<URL> response_code=400 return_code=ok total_time=0.484651
ETHON: performed MULTI
```

However, if I set my `max_concurrency` to 10, everything works.

Any thoughts as to why this might be occurring? Is it a problem with Typhoeus or Ethon?

I tried passing higher values of `max_total_connections` and `maxconnects` when initializing the `Typhoeus::Hydra` but it didn't seem to help.

libcurl version:

```
$ curl-config --version
libcurl 7.30.0
```

**Comment by asross** [comment]
This was using the Faraday adapter, by the way... if that's relevant.

**Comment by i0rek** [comment]
@asross thanks for your report. Maybe your issue is resolved in the latest libcurl release. If it is not, let me know. Did you set timeouts?

**Comment by acrogenesis** [comment]
I get this same error using typhoeus, I'm using heroku. libcurl version:
```
curl-config --version
libcurl 7.35.0
```

**Comment by eltone** [comment]
typhoeus/ethon#125 fixes the repro in #411 on MRI 2.2.1 for me. @i0rek would it be possible to create a release(s) that includes that change please?

**Comment by i0rek** [comment]
@eltone I released ethon 0.9.1 last night.

**Comment by eltone** [comment]
@i0rek Great! Thanks so much.

**Comment by asross** [comment]
Feel free to close this issue if you guys believe it's solved!
