### ISSUE TITLE
Resolve only

### ISSUE THREAD

**Issue by Zapotek** [typhoeus/typhoeus#482]
This isn't actually an issue but I was wondering if there's a trick I can use to check if a domain name can be resolved, but without attempting to connect to the remote server, via the normal request interface.

Maybe a combination of time out options or something?
Monkey-patching Typhoeus and/or Ethon would be fine too.

**Comment by i0rek** [comment]
I don't know about a good way to do that, other than requesting an url like normal.

**Comment by Zapotek** [comment]
Fair enough, thanks.

**Comment by AvnerCohen** [comment]
I could well be missing using the `host` command line?
http://linux.die.net/man/1/host

**Comment by Zapotek** [comment]
There are plenty of alternatives, I was hoping I could get do the resolution via the usual Typhoeus request API.

**Comment by AvnerCohen** [comment]
oh, I see, cool +1:
