### ISSUE TITLE
Typhoeus much slower when request headers are included

### ISSUE THREAD

**Issue by tomgallagher** [typhoeus/typhoeus#495]
I'm making a standard Typhoeus request:

`request = Typhoeus::Request.new("http://www.google.com/", headers: {'User-Agent' => user_agent},  method: :get, proxy: proxy, proxyuserpwd: 'blah', followlocation: true)`

Here's the cURL equivalent:

`curl -s -w "%{time_total}\n" -A "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36" -x http://blah -o outfile.htm https://www.google.com`

When I make the request in cURL, it's taking 0.6 seconds. When I do it through Typhoeus, it's taking 1.6 seconds. I take out the user agent header, the times are roughly the same. I can't work out why this might be. Has anyone ever seen this problem before? Am I just being dense?

**Comment by Zapotek** [comment]
I would be very surprised if it had to do with the headers, it could be due to Typhoeus being configured to `followlocation` though.

Here are my results (used `http` for all):

```
2.2.3 :002 > Typhoeus::Request.get("http://www.google.com/", headers: {'User-Agent' => user_agent}, method: :get ).time
 => 0.181685 
```

```
2.2.3 :003 > Typhoeus::Request.get("http://www.google.com/", headers: {'User-Agent' => user_agent}, method: :get, followlocation: true ).time
 => 1.180494 
```

```
$ curl -s -w "%{time_total}\n" -A "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36" http://www.google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.gr/?gfe_rd=cr&amp;ei=iKpwVsfiN4yCaKigqCA">here</A>.
</BODY></HTML>
0.183
```

**Comment by Zapotek** [comment]
Also, if you're experimenting with this in IRB or otherwise working from the same process, the first call will always take the longest, subsequent ones will reuse the existing connection and be much faster.

Trying my first example again results in:
```
2.2.3 :003 > Typhoeus::Request.get("http://www.google.com/", headers: {'User-Agent' => user_agent}, method: :get ).time
 => 0.077626 
```

**Comment by tomgallagher** [comment]
I can repeat your results on irb, with the simple get request. Agreed that followlocation would increase the time. The request set out above is run in the hydra,  which I'm testing in a rake task, not sure why headers should pose a problem in the hydra.

But it remains true that if I run my benchmark test with the headers and then only remove the headers, the response.appconnect_time drops from 1.5 secs to close to zero and the response.total time falls by more than 50% (2.6 to 1.2 secs).

Here's the rake task in full:

`desc "Test Proxies"
task :test_proxies => :environment do
  require 'typhoeus'
  
    file_source = "#{Rails.root}/lib/proxy_text_files/full_list_nopl/ninja.txt"
    proxy_array = File.readlines(file_source)
    
    #get a list of user agents
    @user_array = File.open("#{Rails.root}/lib/UserAgentStrings.txt").readlines.map(&:strip)
    
    hydra = Typhoeus::Hydra.new
    results_array = []
    proxy_array.each do | proxy|
        user_agent = @user_array.sample.to_s
        request = Typhoeus::Request.new("http://www.google.com/", headers: {"User-Agent" => user_agent}, method: :get, proxy: proxy, proxyuserpwd: 'blah', followlocation: true)
        request.on_complete do |response|
            results_array.push(response.code)
            results_array.push(response.appconnect_time)
            results_array.push(response.total_time)
        end
        hydra.queue(request)
    end
    hydra.run
    puts results_array
end`

**Comment by Zapotek** [comment]
Can you reproduce that behavior with a simple script without using proxies?

What you're describing sounds like connections not being reused and the proxies could have something to do with that.
Logging response headers along with the time data could help, `Connection` headers for example would explain this.
No idea why that would happen only if you're set a UA string, but my point is that right know a lot of things could play a part in this, so better start with a clean example without proxies.

**Comment by tomgallagher** [comment]
Yes, that's a good idea. I have run the script without proxies and the difference between the headers/without headers requests is proportionately the same, but the requests are happening much quicker. So with headers, 0.4 sec response.total_time, without headers 0.2 secs response.total_time.

Could you explain a bit more about `Connection` headers and how that might help me understand where I'm going wrong?

**Comment by Zapotek** [comment]
About the `Connection` headers, it wouldn't be anything you're doing.

If a client receives a response header like `Connection: close` it will close the connection, so if that happens a lot new connections will have to be established while the requests are being performed, instead of reusing existing ones.

Variations ranging between 0.2-0.4s for HTTP responses could be random, how consistent are the times for both cases?
Also, could you post the script to make sure that we're both working from the same benchmark?

**Comment by Zapotek** [comment]
```ruby
require 'ap'
require 'typhoeus'

user_agent = 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'

data = []

hydra = Typhoeus::Hydra.new

20.times do |i|
    request = Typhoeus::Request.new(
        'http://www.google.com/',
        headers: {
            'User-Agent' => user_agent
        }
     )

    request.on_complete do |response|
        ap "Got #{i}"
        data << [response.code, response.time, response.app_connect_time]
    end

    hydra.queue request
end

hydra.run

avg_time             = 0
avg_app_connect_time = 0

data.each do |code, time, app_connect_time|
    avg_time             += time
    avg_app_connect_time += app_connect_time
end

ap avg_time / Float( data.size )
ap avg_app_connect_time / Float( data.size )
```

The above consistently yields 0.4s `avg_time` with and without request headers for me.

**Comment by tomgallagher** [comment]
I don't know if this will mean anything to anyone.

When I send the Typhoeus request with no headers through the proxy, I get these response headers back from Google:

`{"Date"=>"Wed, 16 Dec 2015 11:24:29 GMT", "Expires"=>"-1", "Cache-Control"=>"private, max-age=0", "Content-Type"=>"text/html; charset=ISO-8859-1", "P3P"=>"CP=\"This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info.\"", "Server"=>"gws", "X-XSS-Protection"=>"1; mode=block", "X-Frame-Options"=>"SAMEORIGIN", "Set-Cookie"=>["NID=74=G8UgcX_oJOyEeuPheY3fexJc1gHJrx0sdPtbwbLonFZi7gIoVpIDPSXXlovUMfNi8Vt-dzaUjQCVKP2As_oozUdYnyr7xO8NrXULk9TaMeq0fG8cbtWkqPwqH-LODbGQ; expires=Thu, 16-Jun-2016 11:24:29 GMT; path=/; domain=.google.it; HttpOnly", "CONSENT=CG.24e1d4; expires=Sat, 16-Jan-2016 11:24:29 GMT; path=/; domain=.google.it"], "Accept-Ranges"=>"none", "Vary"=>"Accept-Encoding", "Transfer-Encoding"=>"chunked", "Connection"=>"keep-alive"}`

When I send it with headers through the proxy, I'm getting these headers:

`{"Date"=>"Wed, 16 Dec 2015 11:22:58 GMT", "Expires"=>"-1", "Cache-Control"=>"private, max-age=0", "Content-Type"=>"text/html; charset=UTF-8", "P3P"=>"CP=\"This is not a P3P policy! See https://www.google.com/support/accounts/answer/151657?hl=en for more info.\"", "Server"=>"gws", "X-XSS-Protection"=>"1; mode=block", "X-Frame-Options"=>"SAMEORIGIN", "Set-Cookie"=>["NID=74=mLIi_WlGsmPn6v4jY6R18dwpx03iHpojEBCZ89jjRezNG2yi3tOym4CxLNC1_sTGcXIIVv5ZFOdRJl_hq2zzNzBxHQJuRpY8I81HoIBbUUcHZNeSSgZ4lVvsGsqGZWuZ; expires=Thu, 16-Jun-2016 11:22:58 GMT; path=/; domain=.google.it; HttpOnly", "CONSENT=WP.24e1d4; expires=Fri, 01-Jan-2038 00:00:00 GMT; path=/; domain=.google.it"], "Alternate-Protocol"=>"443:quic,p=0", "Alt-Svc"=>"quic=\"www.google.com:443\"; ma=600; v=\"30,29,28,27,26,25\"", "Accept-Ranges"=>"none", "Vary"=>"Accept-Encoding", "Transfer-Encoding"=>"chunked"}`

I don't know if it's significant that the Connection: Keep Alive header is missing from the second one. And the addition of Alt-SVC, ma and v headers might mean something to someone. Help!

**Comment by Zapotek** [comment]
Looks like the proxy is biased towards your UA.
Does it happen when the headers include a UA or if there are any user-set headers in general?

**Comment by tomgallagher** [comment]
OK it seems that this problem was nothing to do with Typhoeus, so apologies for posting in error. I chose Google for a test site to measure speed and that was a mistake. They are the only people who did not reply to my request through the proxy with a Connection:Keep Alive header, thereby causing the delays. Why they are doing this is beyond me, but it seems as if Google may be operating a policy on proxy server requests. Thanks for all your help and patience.

**Comment by i0rek** [comment]
@tomgallagher @Zapotek thanks for your work! :)
