### ISSUE TITLE
Gem not found 404 error during installation

### ISSUE THREAD

**Issue by vilbeyli** [typhoeus/typhoeus#499]
I have `ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]` on Windows 10 x64 machine.
When I try to install typhoeus

    gem install typhoeus

I get

    ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
        bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/gems/typhoeus-0.8.0.gem)

How can I workaround this issue?

**Comment by vilbeyli** [comment]
OK, I'm not sure if anything is done to fix this but I tried `gem install typhoeus` and it just installed the gem.

**Comment by i0rek** [comment]
Thanks for reporting @vilbeyli. Sounds like it was a problem with the gemservers. I am glad it is solved.
