### ISSUE TITLE
how to know the downloaded webpage encoding?

### ISSUE THREAD

**Issue by xobius** [typhoeus/typhoeus#509]
I have done a spider that crawl webpages with encoding like ISO-8859-1 , UTF-8 or Windows 1252. When  the event  request.on_complete run,  I do
"puts response.body.to_s.encoding"
  Althougth, the Ruby Internal Encoding is set to ISO8859-1 or UTF-8, it show me, always, ASCII-8bit,
How I could know  the downloaded text encoding? 

Thanks in advance

**Comment by skalee** [comment]
@xobius I believe it's out of the scope of this gem. This gem is for making HTTP requests whereas charset is defined in HTML or XHTML document (e.g. with [meta tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset)). Typhoeus knows nothing about HTML, what you need is to employ some HTML parser. Perhaps [Nokogiri](https://rubygems.org/gems/nokogiri/versions/1.6.7.2) would be useful?

**Comment by xobius** [comment]
Thanks, so much by your answer. It was useful.
