### ISSUE TITLE
forcing TLSV1.1 or higher on SSL for Typhoeus 1.0.1 possible bug

### ISSUE THREAD

**Issue by restlest** [typhoeus/typhoeus#513]
I can't see a way to specifically request an HTTPS connection using TLSV1.2 or even TLSV1.1
We are using curl version 7.19.1 but despite what I've read about this version, I can make a connection with TLSV1.2  by using --tlsv1. It must be a patched distribution.

The CipherSuites say it all

curl --tlsv1 -v -i -L -H 'Accept: application/json'  <https site>
* Connected to ...
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_RSA_WITH_AES_256_CBC_SHA256

With a simple Typhoeus request (not using Hydra or Faraday):
ETHON: Libcurl initialized
Connected to ...
Initializing NSS with certpath: sql:/etc/pki/nssdb
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
SSL connection using TLS_RSA_WITH_RC4_128_SHA

Is there a configuration option for sslversion that I can set to make this work?
Using ssl_version doesn't work as I get a deprecation message

It seems to me if CURL can operate with the option to remove TLSV1 then configuring Typhoeus should allow specifying which CipherSuite to use but the options aren't passed on.

For what it's worth our NSSDB configurations use something like this but I'm unclear about editing it. It's probably a bad idea.
NSS=Flags=internal,moduleDBOnly,critical trustOrder=75 cipherOrder=100 slotParams=(1={slotFlags=[RSA,DSA,DH,RC2,RC4,DES,RANDOM,SHA1,MD5,MD2,SSL,TLS,AES,Camellia,SEED,SHA256,SHA512] askpw=any timeout=30})

**Comment by restlest** [comment]
Looks like the solution is to use sslversion: :tlsv1

**Comment by i0rek** [comment]
glad it works, thanks for reporting!
