### ISSUE TITLE
Ssl avoidance problem

### ISSUE THREAD

**Issue by donFotter** [typhoeus/typhoeus#530]
Hi, I'm developing new Api for my service with Swagger. Everything is fine, but when I test the generated ruby's client, I have problem with the ssl avoidance. More specifically, I've set a variable, "verify_ssl" to false, but this doesn't work, so the code try to verify ssl, getting error. With other client(python, nodejs, php), the same operation works. I've opened a issue on swagger-codegen git and they suggest to contact you, meaning that this could be a typhoeus bug. 
What can I do? 
This is the link with all the discussion: https://github.com/swagger-api/swagger-codegen/issues/3269

**Comment by i0rek** [comment]
@donFotter thanks for reporting! Did you set `ssl_verifyhost` and/or `ssl_verifypeer` as described in https://github.com/typhoeus/typhoeus#ssl?

**Comment by donFotter** [comment]
Hi i0rek! Changing ssl_verifyhost solved the problem! The fact is that this option wasn't in the generated swagger code, so I've add it. Now I'm going back to the original discussion to report this fix. Thank you very much!

**Comment by i0rek** [comment]
I am glad to hear that!
