### ISSUE TITLE
[Question] Unix socket support

### ISSUE THREAD

**Issue by dopykuh** [typhoeus/typhoeus#538]
Since curl 7.40 it supports unix socket support. Is typhoeus or ethon able to handle them?

**Comment by i0rek** [comment]
Not yet. https://curl.haxx.se/libcurl/c/CURLOPT_UNIX_SOCKET_PATH.html is not part of ethon yet. But that shouldn't be hard to add.

**Comment by dopykuh** [comment]
Ok, that sounds great. It should only be added in lib/ethon/curls/options.rb, right?

**Comment by i0rek** [comment]
I think so!

**Comment by dopykuh** [comment]
[Pull request](https://github.com/typhoeus/ethon/pull/128) opened.
