### ISSUE TITLE
Adding delay?

### ISSUE THREAD

**Issue by 9mm** [typhoeus/typhoeus#540]
Hi, I'm wondering if there's a way, either with an undocumented setting or some type of before callback, for me to set down an offset in `ms`, say `100ms`. That way if I'm making a lot of requests a once I can have them staggered just by a fraction of a second (but still of course much faster than running them serially).

Thanks!

**Comment by i0rek** [comment]
There is no such thing.

**Comment by 9mm** [comment]
This works perfectly actually:

        Typhoeus.before do |request|
          sleep 0.100
        end

**Comment by 9mm** [comment]
It starts all the requests with 100ms in between so its just not 100% all at once

**Comment by i0rek** [comment]
this is something build into typhoeus. if the behaviour is what you want, you should use it. this has nothing to do with libcurl though and doesn't affect its behaviour. When using the hydra, it means that every time you add a request, it takes 100ms. Adding them to the hydra is delayed, not the actual execution.

**Comment by 9mm** [comment]
Damn.... I see. So yeah Nevermind that's not what I want
