### ISSUE TITLE
Frequent `recv_error`s recently (libcurl version issue?)

### ISSUE THREAD

**Issue by rmosolgo** [typhoeus/typhoeus#547]
Hi there! Thanks for your work on this gem. I discovered it in the source of my application when hunting a bug, and looking at your documention, I can see that Typhoeus is really powerful!

I work on a stable (legacy) application which depends on a _another_ service running on `localhost:2112`. 

Our usage of Typhoeus was comically small: 

```ruby 
Typhoeus.get(service_url)
```

Recently (around Nov 8), calls to that remote service started failing. I was surprised, because we rarely change the code in this application _or_ in the remote service. They've been running smoothly for about two years. 

I started logging the response `options` in failure cases:

```js 
{
  "httpauth_avail": 0,
  "total_time": 0.001906,
  "starttransfer_time": 0,
  "appconnect_time": 0.00002,
  "pretransfer_time": 0.000053,
  "connect_time": 0.00002,
  "namelookup_time": 0.000019,
  "redirect_time": 0,
  "effective_url": "http://localhost:2112/event_template/1551110/resource/105136.json",
  "primary_ip": "127.0.0.1",
  "response_code": 0,
  "request_size": 292,
  "redirect_count": 0,
  "return_code": "recv_error",
  "response_headers": "",
  "response_body": "",
  "debug_info": "[OBJECT]"
}
```

As you can see, it has `response_code: 0` and `return_code: recv_error`. I logged the `message` too: 

```
Failure when receiving data from the peer
```

The logs for the remote service had _no record_ of receiving the request. It seems like it never actually sent! 

We couldn't figure out what was going on, but we recognized "recv_error" as an error message from `libcurl` (perhaps code `56`), so we swapped `Typhoeus` for `Net::HTTP`. We weren't taking advantage of Typhoeus's awesome parallelism features, so the switch was straightforward. Since switching, we haven't seen any errors.

So, I'm not sure if there's anything to be done here, but I wanted to make a record in case anyone else sees a problem, probably coming from `libcurl`! I doubt there's anything "wrong" with Typhoeus, since the error message is coming from a "lower level".

Thanks again for all your work on this gem! If we need a more robust HTTP client down the road, I know where to look!

**Comment by i0rek** [comment]
@rmosolgo thanks for reporting! Did you close this issue because your problem was fixed or because you just wanted to let me know?
