### ISSUE TITLE
Passing Typhoeus options to Faraday adapter

### ISSUE THREAD

**Issue by soedar** [typhoeus/typhoeus#549]
Currently, there seems to be no way to pass Typhoeus specific options to be applied for every request when using the Faraday adapter. 

For our use case, we need to pass in `forbid_reuse: true` for each request, otherwise our application will end up with a lot of open connections [(Details)](http://stackoverflow.com/questions/12559575/typhoeus-does-not-close-https-connections). We have been monkey patching the adapter, but that is clearly not sustainable.

Taking reference from Faraday's [excon adapter](https://github.com/lostisland/faraday/blob/d2f000be485c0d8c005959638076a87d4416f57f/lib/faraday/adapter/excon.rb), we can implement the `initialize` method in the adapter, which will allow us to take configuration options from Faraday's conn initialization and merge to it every request.

Here's how the Faraday initialization could look like:
```ruby
conn = Faraday.new(url: "www.example.com") do |faraday|
    faraday.adapter :typhoeus, forbid_reuse: true
end
```

If this looks okay, I can work on this and open a PR with these changes.

**Comment by i0rek** [comment]
Hi @soedar, that looks good! I would certainly merge such PR.
