### ISSUE TITLE
max_recv_speed_large doesn't seem to be respected

### ISSUE THREAD

**Issue by scalp42** [typhoeus/typhoeus#556]
```ruby
        curl = Typhoeus.get(
          'example.com',
          followlocation: true,
          timeout: 10,
          headers: {
            'User-Agent' => 'user-agent',
          },
          max_recv_speed_large: 20000
        )
```

Trying to set a 20kb limit but it doesn't appear to be respected looking at traffic (maxes out the interface). Any idea?

**Comment by Zapotek** [comment]
You've put `max_recv_speed_large: 20000` inside the `:headers`.

**Comment by scalp42** [comment]
Sorry was editing the response. Looking more at curl docs, it's not an exact limit so I'm going to close this.
