### ISSUE TITLE
Async scripts not in response.body

### ISSUE THREAD

**Issue by tomgallagher** [typhoeus/typhoeus#559]
Hi

I'm trying to get an idea of the scripts on any page, say [Youtube](http://www.youtube.com). Using Typhoeus to get the page, it does not return any scripts with the HTML 5 async tag added, as these seem to be added in a later request.response cycle in the browser.

Anyone come across this and can suggest a workaround? I could use a headless browser but all very much slower than Typhoeus-speed.

Thanks

Tom

**Comment by i0rek** [comment]
Hello @tomgallagher, thats not as easy. I guess the other stuff is loaded by some js. This is nothing typhoeus can help you with.
