### ISSUE TITLE
Is it possible to only cache on specified response codes?

### ISSUE THREAD

**Issue by griest024** [typhoeus/typhoeus#561]
I want to do something like `Typhoeus.get(url, acceptable_response_codes_for_cache: [200, 201])` and have the response cached only if it has a code of 200 or 201.

[Here](https://gist.github.com/griest024/17894675283fc3aca07de641c2f61750) is an example implementation of what I mean.

I'm using rails.

**Comment by i0rek** [comment]
@griest024 you should just tailor the existing caches to your needs. I am hesitating to add it to the caches in typhoeus since this sounds very specific.

**Comment by griest024** [comment]
I am currently handling this logic in my custom cache. However, this means that the response codes can only be specified per cache, as opposed to per request. It would be more versatile to specify codes per request.

I understand your reluctance to add this, although I thought this would be a useful feature to have.
