### ISSUE TITLE
Enqueue hydra with other hydra (compound requests)

### ISSUE THREAD

**Issue by fatuhoku** [typhoeus/typhoeus#565]
I like the compositional nature of hydra; you can define what needs to happen once requests complete.

But for complex operations you might want to split up the hydra movements into different functions.

Was Hydra designed to enqueue other hydra?

**Comment by i0rek** [comment]
@fatuhoku thanks for your question! Hydra was designed for that type of workload. Hydra wraps libcurl's multi, you can read more about its capabilities and limitations here: https://curl.haxx.se/libcurl/c/libcurl-multi.html.
