### ISSUE TITLE
Stubbed requests are incompatible with Faraday 0.12.2

### ISSUE THREAD

**Issue by pablobm** [typhoeus/typhoeus#574]
Faraday 0.12.2 is incompatible with Typhoeus's stubbed responses. This is the relevant change: https://github.com/lostisland/faraday/commit/b2e8bcc. This affects third-party tools such as WebMock.

The problem is with the new headers parser in Faraday. It assumes that there will be a status line in the response (eg: `HTTP/1.1 200 OK`). When this is not present, it breaks with a `TypeError` due to an unexpected `nil`.

This is the reason why the build is failing at the moment. Here's a short reproduction:

```ruby
require "typhoeus"
require "typhoeus/adapters/faraday"

url = "http://www.example.org/"

conn = Faraday.new(url) do |faraday|
  faraday.adapter :typhoeus
end

mock_response = Typhoeus::Response.new(
  code: 200,
  headers: {
    "Content-Type": "text/html",
  },
  mock: true,
)

Typhoeus.stub(url).and_return(mock_response)
begin
  conn.get
  puts "Yay, all is good! :-)"
rescue TypeError
  puts "Faraday didn't like our stubbed response X-("
end
```

I would happily put together a PR for this... but I'm not sure which of the two projects should be fixed. Faraday is correct in assuming that there must be a status line, but it could be argued that (a) theirs is a back-incompatible change, and (b) `Faraday::Utils::Headers#parse` is a misleading name, as it expects a status line as well as headers.

Thoughts?

**Comment by i0rek** [comment]
Thank you for your investigation. I would be fine changing typhoeus. If
you would provide a PR i would happily merge it!

On Fri, Aug 11, 2017, at 04:13 PM, Pablo Brasero wrote:
> Faraday 0.12.2 is incompatible with Typhoeus's stubbed responses. This
> is the relevant change: lostisland/faraday@b2e8bcc. This affects third-
> party tools such as WebMock.> The problem is with the new headers parser in Faraday. It assumes that
> there will be a status line in the response (eg: HTTP/1.1 200 OK).
> When this is not present, it breaks with a TypeError due to an
> unexpected nil.> This is the reason why the build is failing at the moment. Here's a
> short reproduction:


> require "typhoeus" require "typhoeus/adapters/faraday"  url = "
> http://www.example.org/"  conn = Faraday.new(url) do |faraday|
> faraday.adapter :typhoeus end  mock_response = Typhoeus::Response.new(
> code: 200, headers: { "Content-Type": "text/html", }, mock: true, )
> Typhoeus.stub(url).and_return(mock_response) begin conn.get puts "Yay,
> all is good! :-)" rescue TypeError puts "Faraday didn't like our
> stubbed response X-(" end
>> I would happily put together a PR for this... but I'm not sure which
> of the two projects should be fixed. Faraday is correct in assuming
> that there must be a status line, but it could be argued that (a)
> theirs is a back-incompatible change, and (b)
> Faraday::Utils::Headers#parse is a misleading name, as it expects a
> status line as well as headers.> Thoughts?


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/typhoeus/typhoeus/issues/574
