### ISSUE TITLE
Support GET requests with Body contents

### ISSUE THREAD

**Issue by icy** [typhoeus/typhoeus#586]
Some API requires body contents in GET request, e.g, ElasticSearch. Is it possible to support them in typhoeus?

**Comment by PericlesTheo** [comment]
@icy  Have you tried by any chance `Typhoeus::Request.new(endpoint, method: :get, body: my_body).run`?

**Comment by PericlesTheo** [comment]
@icy any chance you had a look at the above?

**Comment by icy** [comment]
hi @PericlesTheo , yes that works perfectly. Thanks a lot and I'm sorry for my belated response.
