### ISSUE TITLE
JSON.parse in a middleware, callback or adapter?

### ISSUE THREAD

**Issue by mmahalwy** [typhoeus/typhoeus#589]
Is there a way to handle response body with `JSON.parse` in a form of a middleware, callback or adapter?

**Comment by PericlesTheo** [comment]
I don't think so but depending what you need you might be able to use https://github.com/lostisland/faraday with Typhoeus as the adapter. 

What's the use case?

**Comment by mmahalwy** [comment]
@PericlesTheo the use case is I found myself having to do the json parsing after the request resolves everytime. Didn't know if there was a better way.

Question about using Faraday + Typhoeus vs Typhoeus on it's own. What are the trade-offs?

**Comment by PericlesTheo** [comment]
@mmahalwy  Faraday gives you some more granular control of things I believe plus it can be used with multiple adapters. However, the code below based on your use case might be enough?

```
require 'json'
require 'typhoeus'
Typhoeus.before do |request|
  request.on_complete do |response|
    if response.success?
      JSON.parse(response.body)
    end
  end
}

Typhoeus.get("https://jsonplaceholder.typicode.com/posts/1").handled_response
=> {"userId"=>1,
 "id"=>1,
 "title"=>"sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
 "body"=>
  "quia et suscipit\n" +
  "suscipit recusandae consequuntur expedita et cum\n" +
  "reprehenderit molestiae ut ut quas totam\n" +
  "nostrum rerum est autem sunt rem eveniet architecto"}
```

Let me know if the above is what you are after

**Comment by mmahalwy** [comment]
Will give that a try!

**Comment by PericlesTheo** [comment]
@mmahalwy I'm assuming `Typhoeus.before` worked for you and go ahead and close this PR 😄
