### ISSUE TITLE
Unable to use client certificate

### ISSUE THREAD

**Issue by nomasprime** [typhoeus/typhoeus#595]
Hi,

So, in curl this command works as expected:

```
curl --cert certificate.pem --key key.pem "https://url" -k
```

But in Typhoeus this fails:

```
Typhoeus.get(
  "https://url",
  sslcert: OpenSSL::X509::Certificate.new(File.read('certificate.pem')),
  sslkey: OpenSSL::PKey::RSA.new(File.read('key.pem')),
  ssl_verifypeer: false,
  ssl_verifyhost: 0
)
```

The error message in Typhoeus' debug reads:

```
unable to use client certificate (no key found or wrong pass phrase?)
```

Doesn't make any sense to me but hopefully someone else can help?

**Comment by nomasprime** [comment]
Is there a way to see the curl command?

**Comment by nomasprime** [comment]
Not sure why but restarting console changed the error message to empty response from server.

**Comment by nomasprime** [comment]
So, somehow I introduced another problem. Now that's fixed I'm back to this issue.

**Comment by nomasprime** [comment]
Reload and back to first issue again 😕

**Comment by nomasprime** [comment]
I'm investigating this issue with a fresher brain.

The first error, no key found, was my fault: the path to the files was wrong.

The difference in versions was because I was comparing to curl on the host rather than running inside the container. When run inside they're the same.

The problem now is curl succeeds, with the same version, and Typhoeus fails. The error message reads `error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure`.

**Comment by nomasprime** [comment]
Looks like, contrary to other examples, you have to pass paths as args for `sslcert` and `sslkey`.

**Comment by Slotos** [comment]
This is actually still a problem in case keys are being fetched not from a filesystem.
