### ISSUE TITLE
Is here any best practice?

### ISSUE THREAD

**Issue by sblim0126** [typhoeus/typhoeus#599]
i usually using Hydra as instance object
e.g
```
class HttpParallel
  @http_parallel_client = Typhoeus::Hydra.hydra
  @http_parallel.max_concurrency = 400
end
```
and make 20~30 request and queueing and run
but sometimes happen 504 bad gateway issue

is it right way?

I need to make New Hydra object per request?

**Comment by i0rek** [comment]
No, you are doing it right. Maybe the server cannot handle that many request?
