### ISSUE TITLE
Bump version to 1.3.1

### ISSUE THREAD

**Issue by zachwalton** [typhoeus/typhoeus#607]
Hi there!

I was hoping to get a version 1.3.1 published to rubygems to pull in https://github.com/typhoeus/typhoeus/pull/600. I'd open a PR but don't know the release process.

Here's the current diff: https://github.com/typhoeus/typhoeus/compare/v1.3.0...master

WDYT? Would this be possible?

**Comment by zachwalton** [comment]
No problem, thank you!

**Comment by Dbz** [comment]
Hello! Just stopping by to say I'd also love some of the changes in the diff. Thank you @i0rek for the gem!

**Comment by i0rek** [comment]
Thanks for the reminder, `1.3.1` is published now!
