### ISSUE TITLE
Bug: Response code is 0 when it should be 301

### ISSUE THREAD

**Issue by michaeltelford** [typhoeus/typhoeus#640]
Bug: Response code is 0 when it should be 301

This is happening on typhoeus `v1.3.1`

This is only happening for certain URL's, in this case: http://vereinintro.wordpress.com/

The following demonstrates the incorrect response code:

```sh
$ pry
[1] pry(main)> Net::HTTP.get_response URI('http://vereinintro.wordpress.com/')
=> #<Net::HTTPMovedPermanently 301 Moved Permanently readbody=true>
[2] pry(main)> require 'typhoeus'
=> true
[3] pry(main)> Typhoeus.get('http://vereinintro.wordpress.com/').code
=> 0
```

```sh
$ curl -I http://vereinintro.wordpress.com/
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Sat, 19 Oct 2019 05:44:00 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://vereinintro.wordpress.com/
X-ac: 1.syd _bur 
```

The response code from `Typhoeus.get` should be `301` but is `0`.

**Comment by michaeltelford** [comment]
Another URL that shows the same problem in Typhoeus but not in other libs is: https://vereinintro.com

**Comment by PericlesTheo** [comment]
I can verify that behaviour but I think there is something weird with the server dropping requests based on `User-Agent` headers?

```ruby
response = Typhoeus.get("https://vereinintro.wordpress.com")
response.code
=> 0
response.request.options
=> {:method=>:get, :headers=>{"User-Agent"=>"Typhoeus - https://github.com/typhoeus/typhoeus", "Expect"=>""}, :maxredirs=>50}
```

Now, let's add a silly `User-Agent` header

```ruby
response = Typhoeus.get("https://vereinintro.wordpress.com", headers: { "User-Agent" => "My user agent" })
response.code
=> 301
response.request.options
=> {:headers=>{"User-Agent"=>"My user agent", "Expect"=>""}, :method=>:get, :maxredirs=>50}
```

I'm not sure what the `User-Agent` header (if any) is set with `Net::HTTP`.

If you want to not pass any `User-Agent` header set globally
``ruby
Typhoeus::Config.user_agent = ""
```

so then

```ruby
Typhoeus.get("https://vereinintro.wordpress.com").code
=> 301
```

I hope that helps

**Comment by michaeltelford** [comment]
Yep, changing the User-Agent header from Typhoeus's default one fixed the issue for me. Strange how certain servers dislike the default header.

Thank you @PericlesTheo for the quick response and solution.
