### ISSUE TITLE
add tags for 1.4.0 release

### ISSUE THREAD

**Issue by pravi** [typhoeus/typhoeus#647]
I can see version bumped to 1.4.0 in commits but there is no tags or rubygems.org release. Can you add tags and upload to rubygems.org?

**Comment by michaelirey** [comment]
Looks like there has not been a new version release in years? Yet there is new code in master we would like to use. 

Is there a plan to release another version?

**Comment by i0rek** [comment]
Yes, there will be a new release soon. I just have to get around to do actually doing it. Thanks for caring :)

**Comment by michaelirey** [comment]
Gentle bump on this. Can we assist cutting a new version and release on rubygems? 

The new version of Faraday is no longer compatible with version 1.3.1

**Comment by i0rek** [comment]
https://rubygems.org/gems/typhoeus/versions/1.4.0 the wait is over :) Only required me to install a newer ruby and every around it. :)
