### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by micke** [typhoeus/typhoeus#652]
It would be great if you could cut a new release of typhoeus, we are especially interested in the support for Faraday 1.0 that was fixed in cbab8c9f39167e1ae78ed65e5baeb1dbb53cfbdc.

Thanks!

**Comment by tjwallace** [comment]
Version 1.4.0 was [released today](https://github.com/typhoeus/typhoeus/releases/tag/v1.4.0) 🎉
