### ISSUE TITLE
Getting an error `cannot load such file -- ffi_c` in AWS Ruby Lambda using serverless 

### ISSUE THREAD

**Issue by Karan1909** [typhoeus/typhoeus#680]
Hello , 
I am using a gem that uses `typhoeus` v 1.3.0 in my ruby lambda on aws , runtime: 2.5 

When I try to call a function of my gem, it gives me an error 
```
"errorMessage": "cannot load such file -- ffi_c",
"errorType": "Init<LoadError>",

```

The ruby handler starts off with 

`Ignoring ffi-1.15.3 because its extensions are not built. Try: gem pristine ffi --version 1.15.3
`
I read something about the gem not being pre compiled, though not sure how to use the precompiled version of typhoeus. 

Can anyone suggest what I could be missing in here? Thanks

**Comment by BuonOmo** [comment]
Typhoeus is not the cause, this is likely due to an Ubuntu update. On CircleCI, we could fix it using:

```bash
sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
```

See https://discuss.circleci.com/t/how-to-get-ffi-working-on-ruby-2-7-2-image/37787/2

**Comment by Karan1909** [comment]
Thanks all for your suggestions, I could fix this by compiling and running bundle install in linux docker image using circle ci orb 
https://circleci.com/developer/orbs/orb/codegram/serverless-ruby
to add compiled gems into my gemlayer and that seemed to have fixed the issue
