### ISSUE TITLE
Sending request via proxy

### ISSUE THREAD

**Issue by justinvj15** [typhoeus/typhoeus#81]
I need to integrate typhoeus with tor (http://www.torproject.org/). Is it possible to do like this "Typhoeus::Request.new("www.example.com",:proxy => "#{proxy_ip}:#{proxy_port}")" ?. Can you please tell me how i set proxy in Typhoeus request ?.

Thanks.

**Comment by Valve** [comment]
For those seeking how to use HTTP proxy that requires authentication with Typhoeus:
```
options = {proxy: 'http://proxyurl.com', proxyuserpwd: 'user:password'}
req = Typhoeus::Request.new(url, options)
req.run
```

I only was able to find this info in the Faraday adapter

**Comment by AvnerCohen** [comment]
Maybe PR an example for the readme ?

**Comment by andremedeiros** [comment]
@Valve I agree with @AvnerCohen. A PR with an example in the README would truly be appreciated.

**Comment by Zapotek** [comment]
A bit off-topic but if you're looking for interesting examples of Typheus options have a look at: https://github.com/Arachni/arachni/blob/experimental/lib/arachni/http/request.rb#L310

**Comment by Valve** [comment]
@AvnerCohen, @andremedeiros, done, thanks for the heads up https://github.com/typhoeus/typhoeus/pull/446

**Comment by andremedeiros** [comment]
Merged! :kissing_heart: :heart:

**Comment by Fedcomp** [comment]
@i0rek it seems typhoeus does dns leak and doesn't pass DNS queries through socks5 proxy, which eliminates possibility to use it with onion websites.

**Comment by 9mm** [comment]
Here's the options I used for authenticated socks5

```
      opts = opts.deep_merge(
        proxytype: :socks5,
        proxyport: Settings.socks_proxy.port.to_i,
        proxy: Settings.socks_proxy.host,
        proxyuserpwd: Settings.socks_proxy.username,
        proxypassword: Settings.socks_proxy.password
      ) if use_proxy
```
